services:
  web:
    container_name: gamegalaxy-app
    build: .
    image: gamegalaxy/gamegalaxy:latest
    restart: always
    shm_size: '4gb'
    cap_add:
      - SYS_ADMIN
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096
      - TZ=Europe/Zurich
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - CRON_SECRET=${CRON_SECRET}
      - SHOPIFY_STORE_DOMAIN=${SHOPIFY_STORE_DOMAIN}
      - SHOPIFY_CLIENT_ID=${SHOPIFY_CLIENT_ID}
      - SHOPIFY_CLIENT_SECRET=${SHOPIFY_CLIENT_SECRET}
      - MKM_PROXY_SERVER=${MKM_PROXY_SERVER}
      - MKM_PROXY_USER=${MKM_PROXY_USER}
      - MKM_PROXY_PASS=${MKM_PROXY_PASS}
      - MKM_USER=${MKM_USER}
      - MKM_PW=${MKM_PW}oka
    depends_on:
      - db
    networks:
      - gamegalaxy_net # To talk to Nginx/Internet
      - default # To talk to the Database

  db:
    image: postgres:16-alpine
    container_name: gamegalaxy-db
    restart: always
    environment:
      # These pull the specific values from Portainer
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default # Only accessible by other services in this compose file
      - gamegalaxy_net

volumes:
  db_data:

networks:
  gamegalaxy_net:
    external: true